### ISSUE TITLE
Crash on Server Startup - 1.12.1

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [BenjaminSutter/genera#1]
Hey name Nate more commonly referred to as Zer0. At any rate I have some bad news. Your mod is unhappy either alone or with other mods. At any rate here is the issue.

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows Server 2012 R2 (amd64) version 6.3
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 982387456 bytes (936 MB) / 2050347008 bytes (1955 MB) up to 8520204288 bytes (8125 MB)
	JVM Flags: 8 total; -Xms1g -Xmx8g -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=40 -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSScavengeBeforeRemark -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.41 Powered by Forge 14.22.1.2481 128 mods loaded, 128 mods active

Genera-0.0.5.jar 

https://gist.github.com/P3rf3ctXZer0/5a16be5e524be41bd3daabe4f9bbef88

Good luck and happy modding please let me know if you need pre-release testing.

**Comment by BenjaminSutter** [comment]
This is my fault for not testing servers. I'll get a hotfix out before the end of the night. Thanks for using the mod, I'll get back to you.

**Comment by BenjaminSutter** [comment]
This issue should only exist in the latest version (0.0.5), if it exists where I think it does. I don't advise using anything older though, just give me an hour or so.

**Comment by P3rf3ctXZer0** [comment]
No problem at all; just happy to help. I can't code so I bug test instead. I have a knack for finding bugs.

**Comment by BenjaminSutter** [comment]
I'll get that fix started now.

**Comment by BenjaminSutter** [comment]
File is waiting for approval on CurseForge.

**Comment by BenjaminSutter** [comment]
Approved.

**Comment by P3rf3ctXZer0** [comment]
Does this fix work on 1.12.1 I am staying there till stable 1.12.2 release.

**Comment by BenjaminSutter** [comment]
I haven't tested it, but the update required no code changes, so it should still work. Keep me posted.
