### ISSUE TITLE
Faeries don't go in enclosure

### ISSUE THREAD

**Issue by davqvist** [BenjaminSutter/genera#12]
MC 1.12.2
Genera 1.0.3
Forge 2512

I can't put faeries in an enclosure, if I right click a captured one on an enclosure, the faery just gets released in the world

**Comment by BenjaminSutter** [comment]
This is a weird issue that just appeared last week. It wasn't there in any of my previous tests. I'll figure it out.

**Comment by darkshadow543** [comment]
Ive got the same issue too.

**Comment by BenjaminSutter** [comment]
Fixed in the latest commit.
