### ISSUE TITLE
Wrong Version - Server Rejection 1.12.1

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [BenjaminSutter/genera#2]
https://gist.github.com/P3rf3ctXZer0/5e62dc07d77638aa7d67fe23be920a78

Wrong Minecraft Versions!
Mod: genera
Location: C:\Users\Administrator\AppData\Roaming\.minecraft\1.12.1\mods\Genera-0.0.6.jar
Expected: [1.12.2,1.12.2]
Current: Minecraft 1.12.1

**Comment by BenjaminSutter** [comment]
Alright, looks like what I told you about it still working is incorrect. Sorry.

You might just have to wait until a stable 1.12.2 happens to use Genera. I was certain that would work...

**Comment by P3rf3ctXZer0** [comment]
You didn't include 1.12.1 you did 1.12.2 - 1.12.2 XD
Location: C:\Users\Administrator\AppData\Roaming.minecraft\1.12.1\mods\Genera-0.0.6.jar
Expected: [1.12.2,1.12.2]

**Comment by BenjaminSutter** [comment]
Alright, let me look into it.

**Comment by BenjaminSutter** [comment]
Try the version that just got approved.

**Comment by P3rf3ctXZer0** [comment]
Fixed

**Comment by P3rf3ctXZer0** [comment]
Fixed

**Comment by BenjaminSutter** [comment]
Good, thanks.
