### ISSUE TITLE
Whole stack of Nightshade Seeds gets planted

### ISSUE THREAD

**Issue by davqvist** [BenjaminSutter/genera#3]
MC 1.12.1
Forge 2485
Genera 0.0.6-hotfix

When you plant Nightshade Seeds, the whole stack gets consumed, instead of just one.

**Comment by BenjaminSutter** [comment]
I'll fix this. I didn't realize. Thanks for reporting.

**Comment by BenjaminSutter** [comment]
Fixed for both nightshade and burdock seeds.
