### ISSUE TITLE
Faerie Enclosure Issues

### ISSUE THREAD

**Issue by davqvist** [BenjaminSutter/genera#4]
MC 1.12.1
Forge 2485
Genera 0.0.6-hotfix

The Block should be probably set to transparent as it blocks light and is dark in the middle.
The collision box should be probably lowered to the correct height.
The breaking, walking over model is missing/not defined.
Breaking is instant and the enclosure is deleted.

**Comment by BenjaminSutter** [comment]
Yeah, I know all this stuff. Getting to it. 0.0.7 should fix both your reported issues. Thanks again!

**Comment by BenjaminSutter** [comment]
Fixed.
