### ISSUE TITLE
Nightshade Seeds drop way too frequently

### ISSUE THREAD

**Issue by angelnc1989** [BenjaminSutter/genera#9]
I just installed Genera and wanted to get into it. I broke a lot of tall grass and noticed that the drop rate is insanely high. I got 5 stacks of Nightshade Seeds while only getting 21 vanilla seeds.

**Comment by BenjaminSutter** [comment]
This is something I’ve thought about being a problem but I wasn’t really sure if it was. I’ll fix this when I get home.

**Comment by BenjaminSutter** [comment]
The latest commit fixes this. I'll roll it out with 0.0.8, whenever that happens.
